### ISSUE TITLE
font2img.py error

### ISSUE THREAD

**Issue by Shuolongbj** [kaonashi-tyc/zi2zi#13]
:~/zi2zi$ python font2img.py --src_font=src.ttf \
>                    --dst_font=tgt.otf \
>                    --charset=CN \
>                    --sample_count=1000 \
>                    --sample_dir=dir \
>                    --label=0 \
>                    --filter=1 \
>                    --shuffle=1
Traceback (most recent call last):
  File "font2img.py", line 120, in <module>
    args.sample_count, args.sample_dir, args.label, args.filter)
  File "font2img.py", line 72, in font2img
    src_font = ImageFont.truetype(src, size=char_size)
  File "/Users/Ru/anaconda/envs/gan/lib/python2.7/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/Users/Ru/anaconda/envs/gan/lib/python2.7/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource

@kaonashi-tyc thank you!

**Comment by kaonashi-tyc** [comment]
It seems you didn't provide the right path to your source font through src_font argument. You need to offer a valid ttf/otf font file to point to in order to run the script.

**Comment by Shuolongbj** [comment]
@kaonashi-tyc thank you.where can i get the ttf/otf font file with the tutorial guide

**Comment by Ran-Pan** [comment]
@Shuolongbj you can just google/baidu font ttf download

**Comment by echo-zhouzhou** [comment]
@Shuolongbj  did you solve this problem?

**Comment by mircial** [comment]
@Shuolongbj @kaonashi-tyc what is the specific process?

**Comment by Jiolen** [comment]
> @Shuolongbj @kaonashi-tyc what is the specific process?

你去百度搜索下载ttf或者otf格式的文件，下载好之后放在font2img.py 同一级。
比如我下载的是楷体和华文行楷，文件分别是：simkai.ttf 和 stxingka.ttf

**Comment by yao269220079** [comment]
> 似乎您没有通过src_font参数提供正确的源字体路径。您需要提供一个有效的ttf / otf字体文件来指向该脚本，以运行该脚本。

如何生成自己想要的字符而不是随机采样
