### ISSUE TITLE
The pictures are in the right order

### ISSUE THREAD

**Issue by vVVtreasure** [kaonashi-tyc/zi2zi#17]
package.py
modify：
**pickle_examples(sorted(glob.glob(os.path.join(args.dir, "*.jpg"))), train_path=train_path,                   val_path=val_path,
                    train_val_split=args.split_ratio)**   

so you can get a right order like this:
img dir/0_0000.jpg 0
img dir/0_0001.jpg 0
img dir/0_0002.jpg 0
img dir/0_0003.jpg 0
img dir/0_0004.jpg 0
img dir/0_0005.jpg 0
img dir/0_0006.jpg 0
img dir/0_0007.jpg 0
img dir/0_0008.jpg 0
img dir/0_0009.jpg 0
img dir/0_0010.jpg 0
img dir/0_0011.jpg 0
img dir/0_0012.jpg 0

**Comment by kaonashi-tyc** [comment]
will merge this

**Comment by kaonashi-tyc** [comment]
fixed
