### ISSUE TITLE
how to train 27 different fonts as a single model?

### ISSUE THREAD

**Issue by Revo-Future** [kaonashi-tyc/zi2zi#18]
As mentioned in your blog, u use SIMSUM font as source font , and transfer it to 27 different fonts. how can I train a model that contain 27 different font styles??

**Comment by kaonashi-tyc** [comment]
@Revo-Future 
The font style is represented by its style embedding. You need first, gather data for all 27 fonts. The model will initialize the style embedding, and concat it with the character during training.
