### ISSUE TITLE
ValueError: Could not find a format to write the specified file in mode 'I'

### ISSUE THREAD

**Issue by ALABAMABANANA** [kaonashi-tyc/zi2zi#19]
Hi yc,
I encountered the following error doing interpolation with running infer.py, I've pip installed imageio and ffmpeg  already, how come this error still exists? BTW, actually when i “dpkg -L imageio'' it says imageio is not installed.  I'm not quite sure what is the problem:

Traceback (most recent call last):
  File "infer.py", line 67, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "infer.py", line 62, in main
    compile_frames_to_gif(args.save_dir, gif_path)
  File "/home/Downloads/zi2zi-master/model/utils.py", line 76, in compile_frames_to_gif
    imageio.mimsave(gif_file, images, duration=0.1)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 302, in mimwrite
    writer = get_writer(uri, format, 'I', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/imageio/core/functions.py", line 153, in get_writer
    'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'I'

**Comment by kaonashi-tyc** [comment]
Do you double check the folder that you passed into the compile_frames_to_gif function has nothing but images? If save_dir contains something other than images, it is going to throw this exception

**Comment by ALABAMABANANA** [comment]
yea, nothing but the frames generated. 
so what should I input as the output_gif in " --output_gif=gif_path " ? Is it an empty file under frames directory or something else? Since I checked the code:
"if args.output_gif:
        gif_path = os.path.join(args.save_dir, args.output_gif)
        compile_frames_to_gif(args.save_dir, gif_path)
        print("gif saved at %s" % gif_path)"
I am confused what indeed is this gif_path, seems I need first creat an empty file in 'frames' file.

**Comment by ALABAMABANANA** [comment]
yea, nothing but the frames generated.
However, I figured out the issue was with my input as output_gif. At first I thought the "gif_path" should be a path of the gif file as an empty file, now I realized this argument should be in the format of .gif 
Now mission completed :p

**Comment by ezio1320** [comment]
thank you very much ,bro! You answer helped me!

> yea, nothing but the frames generated.
> However, I figured out the issue was with my input as output_gif. At first I thought the "gif_path" should be a path of the gif file as an empty file, now I realized this argument should be in the format of .gif
> Now mission completed :p

**Comment by Taichi-Pink** [comment]
I am using **Imageio** to read images in **.hdr** format. And I meet this error.
The solution I solved this error is that install plugin to process hdr extension and use the script **imageio_download_bin freeimage** in Pycharm terminal
