### ISSUE TITLE
I would like to apply the project to Chinese calligraphy. I wonder if it is feasible?

### ISSUE THREAD

**Issue by JianChi8** [kaonashi-tyc/zi2zi#22]
For example: I have 3000 character pictures of a calligrapher, I am now looking for a ttf font as a source, with the calligrapher character pictures as the destination for training.
A little bit different from this project, it will appear, the same character, calligrapher will have a variety of writing.
Generated images with ttf font when generated.
Can you predict whether such training can achieve the desired result?
Thank you very much for the project. It was great!

**Comment by JianChi8** [comment]
I found the code below. 
`filter_hashes = set(filter_recurring_hash(charset, dst_font, canvas_size, x_offset, y_offset))`

Filtering is done according to the dst font. 
Does this mean that the same font, one char can be written in a variety of ways?

**Comment by ChuangLee** [comment]
if you mean only one calligrapher, I think is possible。you should add some random input when generating image。
 """ Some characters are missing in a given font, filter them by checking the recurring hashes    """

**Comment by JianChi8** [comment]
Thanks very much!
When I create images with fonts, I find that some words are blank. I will filter them.

I have two questions:
1. Calligraphers have made great changes in their calligraphic works. Do I need to filter out pictures that are totally different between Calligraphy and font,  when preparing for training pictures?
2. Can I train multiple fonts into one font?

Thanks again for your reply

**Comment by ChuangLee** [comment]
1. yeah,I think that would help, you can read the description of   'constant loss '
2. I think it's possible,but what's the meaning?

**Comment by JianChi8** [comment]
Thanks very much。
It seems that I need to try a little more and see the effect.
