### ISSUE TITLE
Using well trained model data and replacing Simsun with other fonts, what's the effect?

### ISSUE THREAD

**Issue by JianChi8** [kaonashi-tyc/zi2zi#23]
I have downloaded the trained model data. I tried the Simsun to a variety of font generation, the effect is very good.

Also try to use other fonts instead of Simsun, to a variety of font generation, the effect is acceptable.

That is to say, the model data is robust and can accept various inputs to generate target fonts.

I wonder if you have tested this situation. What's the effect?

**Comment by kaonashi-tyc** [comment]
@JianChi8 

The model is trained to use SIMSUN as the default source font, so I would assume it won't work very well to use other fonts as sources. You probably need to train a new model, other than using the pre-trained one to generate your target fonts.
