### ISSUE TITLE
How much graphics memory do you need for training? Can you give me a minimum formulation?

### ISSUE THREAD

**Issue by JianChi8** [kaonashi-tyc/zi2zi#27]
How much graphics memory do you need for training? Can you give me a minimum formulation?

**Comment by kaonashi-tyc** [comment]
depends on the your batch size. I use a GTX 1080 and could run up to 32 instances each batch. If GPU memory is your concern, you can try smaller batch size, like 8/16.

**Comment by JianChi8** [comment]
Thanks
