### ISSUE TITLE
where is "embedding" being trained?

### ISSUE THREAD

**Issue by youngjung-obsolete** [kaonashi-tyc/zi2zi#29]
Hi, thanks for sharing nice work.

I guess embedding of each font should be trained somewhere.
init_embedding() creates the embedding variable under scope "embedding" but I cannot find it being used in any optimizer.
d_optimizer trains variables with prefix "d_" and g_optimizer trains "g_" where none of both includes "embedding" or "E".

Could you provide some explanation?

**Comment by ChuangLee** [comment]
I think it's  discriminator
 `fc2 = fc(tf.reshape(h3, [self.batch_size, -1]), self.embedding_num, scope="d_fc2")`

**Comment by youngjung-obsolete** [comment]
Thanks for your prompt reply.
fc2 is for classification regarding id of fonts, i.e., Mingchao/Cursive/Brush.

What I meant by embedding is their respective embedding space.
Something like https://www.tensorflow.org/images/linear-relationships.png
For font domain, yellow and red in tense corresponds to Mingchao and Cursive in fonts.

Have I mistaken something?

**Comment by kaonashi-tyc** [comment]
The embedding is immutable during the training. In a sense it is not embedding per say, functionality wise it is closer to a one-hot vector indicating the id.

**Comment by youngjung-obsolete** [comment]
Thank you so much :)
