### ISSUE TITLE
How to use the pretrained model?

### ISSUE THREAD

**Issue by gdshen** [kaonashi-tyc/zi2zi#3]
Awesome Project! But i can not figure out how to the pretrained model. Should we put the pretrained model into the directory experiment/checkpoint/? Does it need rename?

**Comment by kaonashi-tyc** [comment]
The pretrained model is for inference only, containing only the generator weights. To use it, you can place it wherever u like just point the model_dir argument to the directory that contains the 'checkpoint' file.

**Comment by gdshen** [comment]
Thank you very much!

I am also confused with the parameter `--source_obj` in infer.py, should it be pointed to the `val.obj` we generate early or some other `test.obj`?(I was taught that datasets used in machine learning often be splited into three parts namely train/val/test? But i have not found the procedure to generate test data here?

(Sorry for the wrong operation of closing this issue.)

**Comment by kaonashi-tyc** [comment]
The source_obj could be whatever you want, on the assumption that it is generated by the package.py script just to comply with the the format.

**Comment by gdshen** [comment]
Thank you for your reply.
