### ISSUE TITLE
how much font data is needed?

### ISSUE THREAD

**Issue by hello-world-zsp** [kaonashi-tyc/zi2zi#4]
awesome job!
I'm wondering how many kinds of fonts, characters are needed for training this model? 
meanwhile, could you please share the dataset? thank you.

**Comment by kaonashi-tyc** [comment]
The details could be found in the blog: https://kaonashi-tyc.github.io/2017/04/06/zi2zi.html

As to the dataset, I am afraid I cannot help due to copyrights issue.

**Comment by hello-world-zsp** [comment]
okay, thank you~
