### ISSUE TITLE
package.py: error: argument --split_ratio: invalid float value: '[0,1]'

### ISSUE THREAD

**Issue by chikiuso** [kaonashi-tyc/zi2zi#40]
Hi, I got the following message when running package.py : 

package.py: error: argument --split_ratio: invalid float value: '[0,1]'

Any hints I could solve it? thanks!

**Comment by chikiuso** [comment]
Sorry for raising the unnecessary question, I solved it, thanks!

**Comment by TLHorse** [comment]
Wait a moment, I've got the same question, how did @chikiuso solve it?
