### ISSUE TITLE
如何利用作者的font27模型接着训练

### ISSUE THREAD

**Issue by miraclezqc** [kaonashi-tyc/zi2zi#44]
由于自身GPU太菜，希望拿作者的预训练模型接着训练，但是放在experiment_0_batch_16文件夹下一只报错，是不是需要一些特殊的设置？ 我就是拿简单的两个ttf文件作为src.ttf 和 tgt.ttf，求教~谢谢

**Comment by Nicersmeng** [comment]
作者的模型里只有generator，不是一个完整的checkpoint，肯定不能直接拿来训练了
