### ISSUE TITLE
Considering using a more explicit variable name

### ISSUE THREAD

**Issue by ustcjerry** [kaonashi-tyc/zi2zi#7]
In the code:
```
class UNet(object):
    def __init__(self, experiment_dir=None, experiment_id=0, batch_size=16, input_width=256, output_width=256,
                 generator_dim=64, discriminator_dim=64, L1_penalty=100, Lconst_penalty=15, Ltv_penalty=0.0,
                 embedding_num=1, embedding_dim=128, input_filters=3, output_filters=3):
```
```
self.input_filters = input_filters
self.output_filters = output_filters
```
I think changing `input_filters `and `output_filters` names to `input_channels ` and  `output_channels ` is more explicit.

**Comment by kaonashi-tyc** [comment]
I think whether channels or filters are different preferences by different naming conventions. This one is inherited from https://github.com/yenchenlin/pix2pix-tensorflow repo, which I think it is better leave it for consistency.
