### ISSUE TITLE
如何训练

### ISSUE THREAD

**Issue by lionel-daydayup** [kaonashi-tyc/zi2zi#79]
我

**Comment by Crescentz** [comment]
同问

**Comment by zongzhimin** [comment]
sec-dst形成一对，对应一个label。全部放到一起生成object，一起训练。

**Comment by lionel-daydayup** [comment]
> 我想请问一下是先把27种不同的 src_font和dst_font对应图片生成好放在sample里面，然后一起训练。还是每次生成一对，加载之前的模型训练一次？然后训练27

**Comment by Note-Liu** [comment]
请问就一种label怎么训练？就是把一种手写体转成正楷这种。
