### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [kaonashi-tyc/zi2zi#86]
Hello, what an interesting show!
What I want to know is how to implement brush fonts，as shown in readme like below:
<img width="891" alt="brush" src="https://user-images.githubusercontent.com/36565076/104835541-5e20e780-58e2-11eb-9cc5-a77397253bc5.png">

thanks!

**Comment by caihaunqai** [comment]
您好，我也想复现这个模型，有点不清楚的地方，可以加个联系方式请教和交流下您的进展吗？  主要是category embedding 和 character embedding这部分。
